- name: setup MongoDB
  ansible.builtin.import_role:
      name: common
      tasks_from: mongo-repo


- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed
- name: start & enable service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
- name: enable rempte connection to mongodb
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: restart mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted