
  - name: Install Maven
    ansible.builtin.yum:
      name: maven
      state: installed

  - name: Set-up app(user & directory)
    ansible.builtin.import_role:
        name: common
        tasks_from: app-setup

  

  - name: Install the dependencies(maven package)
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: Load Schema
    ansible.builtin.import_role:
      name: common
      tasks_from: load-mysql-schema

  - name: start application
    ansible.builtin.import_role:
        name: common
        tasks_from: systemd-setup-service


  

  

      





